#cloud-config
write_files:
  - path: "/concourse/keys/web/tsa_host_key"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(tsa_host_key)}
  - path: "/concourse/keys/web/session_signing_key"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(session_signing_key)}
  - path: "/concourse/keys/web/authorized_worker_keys"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(authorized_worker_keys)}
  - path: "/etc/awslogs/awscli.template"
    permissions: "0644"
    owner: "root"
    content: |
      [plugins]
      cwlogs = cwlogs
      [default]
      region = ${region}
  - path: "/etc/awslogs/awslogs.template"
    permissions: "0644"
    owner: "root"
    content: |
      [general]
      state_file = /var/lib/awslogs/agent-state

      [/var/log/concourse.log]
      file = /var/log/concourse.log
      log_group_name = ${log_group_name}
      log_stream_name = {instance_id}
  - path: "/etc/systemd/system/concourse.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Service for Concourse ATC/TSA
      Requires=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      Restart=always
      RestartSec=30s
      TimeoutStartSec=5m
      TimeoutStopSec=1h
      PIDFile=/run/concourse.pid

      ${github_users}
      ${github_teams}
      Environment="CONCOURSE_BASIC_AUTH_USERNAME=${basic_auth_username}"
      Environment="CONCOURSE_BASIC_AUTH_PASSWORD=${basic_auth_password}"
      Environment="CONCOURSE_GITHUB_AUTH_CLIENT_ID=${github_client_id}"
      Environment="CONCOURSE_GITHUB_AUTH_CLIENT_SECRET=${github_client_secret}"
      Environment="CONCOURSE_POSTGRES_DATA_SOURCE=${concourse_postgres_source}"
      Environment="CONCOURSE_EXTERNAL_URL=${concourse_web_host}"
      Environment="CONCOURSE_LOG_LEVEL=${log_level}"
      Environment="CONCOURSE_TSA_LOG_LEVEL=${log_level}"
      Environment="CONCOURSE_TSA_HOST_KEY=/concourse/keys/web/tsa_host_key"
      Environment="CONCOURSE_TSA_AUTHORIZED_KEYS=/concourse/keys/web/authorized_worker_keys"
      Environment="CONCOURSE_SESSION_SIGNING_KEY=/concourse/keys/web/session_signing_key"
      Environment="CONCOURSE_ENCRYPTION_KEY=${encryption_key}"
      Environment="CONCOURSE_OLD_ENCRYPTION_KEY=${old_encryption_key}"

      ExecStartPre=/bin/bash -c "/bin/systemctl set-environment CONCOURSE_PEER_URL=http://$(curl -L http://169.254.169.254/latest/meta-data/local-ipv4):${atc_port}"
      ExecStart=/usr/local/bin/concourse web --aws-secretsmanager-region=${region}

      [Install]
      WantedBy=multi-user.target
  - path: "/etc/systemd/system/concourse-logging.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Service for Concourse logging
      After=rc-local.service

      [Service]
      Type=simple
      Restart=always
      TimeoutSec=infinity

      ExecStart=/bin/bash -c '/usr/bin/journalctl -u concourse --no-tail -f -o cat > /var/log/concourse.log'

      [Install]
      WantedBy=multi-user.target
  - path: "/usr/local/scripts/cloudformation-signal.sh"
    permissions: "0744"
    owner: "root"
    content: |
      #! /usr/bin/bash

      set -euo pipefail

      state=""
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

      until [ "$state" == "\"healthy\"" ]; do
          sleep 10
          state=$(aws --region ${region} elbv2 describe-target-health \
              --targets Id=$${INSTANCE_ID},Port=${tsa_port} \
              --target-group-arn ${target_group} \
              --query TargetHealthDescriptions[0].TargetHealth.State)
          echo "State is $${state}"
      done
runcmd:
  - |
    cp /etc/awslogs/awscli.template /etc/awslogs/awscli.conf
    cp /etc/awslogs/awslogs.template /etc/awslogs/awslogs.conf
  - |
    systemctl enable concourse-logging.service --now
    systemctl enable awslogsd.service --now
    systemctl enable concourse.service --now
  - |
    /usr/local/scripts/cloudformation-signal.sh
    /opt/aws/bin/cfn-signal -e $? --stack ${stack_name} --resource AutoScalingGroup --region ${region}
